inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MixinUsage:
  Exclude:
    - "script/*"

Metrics/AbcSize:
  Max: 65

Metrics/ClassLength:
  Max: 181

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/MethodLength:
  Max: 42

Metrics/PerceivedComplexity:
  Max: 11
