plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 125

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MixinUsage:
  Exclude:
    - "script/*"

Metrics/AbcSize:
  Max: 65

Metrics/ClassLength:
  Max: 240

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/MethodLength:
  Max: 51

Metrics/PerceivedComplexity:
  Max: 11

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/RepeatedExample:
  Exclude:
    - spec/comic_info/issue_spec.rb
